### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by plandolt** [evalandgo/EVCopyBundle#2]
Can you please Tag a new release as you merged the PR https://github.com/evalandgo/EVCopyBundle/pull/1 for symfony 5 support?

**Comment by plandolt** [comment]
Friendly reminder about the Tag :)

**Comment by tilimac** [comment]
Late response but the tag is created ([v1.3.0](https://github.com/evalandgo/EVCopyBundle/releases/tag/v1.3.0))

**Comment by plandolt** [comment]
Thank you, I can finally remove my fork.
